### ISSUE TITLE
when will the ORE project support MSVC14.1?

### ISSUE THREAD

**Issue by jojogh** [OpenSourceRisk/Engine#44] opened 2019-08-15 01:40 UTC
when will the ORE project support MSVC14.1? when I build ORE under MSVC 14.1, build error C2065 popped up, seems ORE is not supporting MSVC14.1 or C++ 14？

**Comment by QuaternionRisk** [comment] 2019-08-15 07:02
MSVC14.1 (Visual Studio 2017) is supported and we use that version daily. You can see this in the auto_link files. This is all documented in the UserGuide, I think we need some small changes for the latest Visual Studio 2019 release.

What are the full build errors?

The ORE coding standards say we allow C++11, to keep it compatible with a wide range of compilers we are not allowing C++14 features yet. I don't see a problem with this, note that QuantLib only allows C++98.

**Comment by jojogh** [comment] 2019-08-15 07:26
I am sure that quantlib is built ok under MSVC 14.1. For ORE, the error info is below, it is a c2065 message, undeclared identifier
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2065	“arguments_”: 未声明的标识符	QuantLib	d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp	53	

1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.hpp(44): error C2516: “QuantLib::FxForward::engine”: 是非法基类 (编译源文件 ql\qle\pricingengines\discountingfxforwardengine.cpp)
1>d:\project\tsquarexl\quantlib\ql\qle\instruments\fxforward.hpp(116): note: 参见“QuantLib::FxForward::engine”的声明 (编译源文件 ql\qle\pricingengines\discountingfxforwardengine.cpp)
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(32): error C3861: “registerWith”: 找不到标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(33): error C3861: “registerWith”: 找不到标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(34): error C3861: “registerWith”: 找不到标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(51): error C2039: “arguments_”: 不是“QuantLib::DiscountingFxForwardEngine”的成员
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.hpp(44): note: 参见“QuantLib::DiscountingFxForwardEngine”的声明
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(53): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(57): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(58): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(59): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(61): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(65): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(66): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(67): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(76): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(80): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(82): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(82): error C2512: “QuantLib::detail::simple_event”: 没有合适的默认构造函数可用
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(82): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(83): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(84): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(86): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(89): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(89): error C2440: “<function-style-cast>”: 无法从“const QuantLib::Currency”转换为“QuantLib::Money”
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(89): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp(90): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.hpp(47): error C2516: “QuantLib::CurrencySwap::engine”: 是非法基类 (编译源文件 ql\qle\pricingengines\discountingcurrencyswapengine.cpp)
1>d:\project\tsquarexl\quantlib\ql\qle\instruments\currencyswap.hpp(112): note: 参见“QuantLib::CurrencySwap::engine”的声明 (编译源文件 ql\qle\pricingengines\discountingcurrencyswapengine.cpp)
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(46): error C3861: “registerWith”: 找不到标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(47): error C3861: “registerWith”: 找不到标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(71): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(72): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(100): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(104): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(109): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(111): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(112): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(115): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(116): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(117): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(118): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(119): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(120): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(125): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(129): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(134): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(135): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(134): error C2660: “QuantLib::CashFlows::npvbps”: 函数不接受 4 个参数
1>d:\project\tsquarexl\quantlib\ql\cashflows\cashflows.hpp(177): note: 参见“QuantLib::CashFlows::npvbps”的声明 (编译源文件 ql\qle\pricingengines\discountingcurrencyswapengine.cpp)
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(137): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(137): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(138): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(139): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(139): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(144): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(145): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(146): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(148): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(151): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(153): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(154): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(156): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(158): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(160): error C2065: “arguments_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(162): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(164): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(166): error C2065: “results_”: 未声明的标识符
1>d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp(167): error C2065: “results_”: 未声明的标识符
1>已完成生成项目“QuantLib.vcxproj”的操作 - 失败。

**Comment by jojogh** [comment] 2019-08-15 07:30
QuantLib is built well under MSVC 14.1, the error is from qle project, the error message is below:
严重性	代码	说明	项目	文件	行	禁止显示状态
error	C2065	“arguments_”: undeclared identifier	d:\ql\qle\pricingengines\discountingfxforwardengine.cpp	53

**Comment by QuaternionRisk** [comment] 2019-08-15 07:32
Hi Alex,

In your first post there, it is QuantLib that is failing to build (discountingfxforwardengine.cpp and discountingcurrencyswapengine.cpp) so whatever you did to fix that is what you need for QuantExt and ORE. I can't read the full error messages but it doesn't look like an MSVC version issue.

**Comment by jojogh** [comment] 2019-08-15 07:40
I think it is a MSVC version issue, because my first build is under MSVC 14.0, as I have to use boost yap which only support MSVC 14.1, so i changed my MSVC to 14.1, the error came out. 
discountingfxforwardengine.cpp and discountingcurrencyswapengine.cpp is the files from ore, and I don't want to use another namespace, and i change namespace the qle to ql, and build it.

**Comment by QuaternionRisk** [comment] 2019-08-15 07:43
Above you have errors in
d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp
d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp
These are QL cpp files so it is the compilation of QL that is failing. You say later QL is working so either you fixed it somehow (in which case do the same thing here) or it is not working (in which case it's a QL problem)

**Comment by jojogh** [comment] 2019-08-15 07:50
My first config is as below, using MSVC 2015(MSVC14.0)
![20190815154628](https://user-images.githubusercontent.com/142501/63080561-f4294380-bf73-11e9-80d4-564203981eb4.png)
this is the config which using MSVC 2017(MSVC14.1), the error came out
![20190815154951](https://user-images.githubusercontent.com/142501/63080714-5f731580-bf74-11e9-83fe-9626b9046603.png)

**Comment by QuaternionRisk** [comment] 2019-08-15 07:54
One of your earlier posts is missing now, did you delete it?

**Comment by jojogh** [comment] 2019-08-15 07:58
Yes, i delete it as it contains a lot of Chinese words.

**Comment by QuaternionRisk** [comment] 2019-08-15 08:01
Ok, it also contains errors in your QL build, as I mentioned above. These are the cause of your problem.

ORE supports Visual Studio 2017, as per the UserGuide.  It builds out of the box using the instructions there. If you are using a different boost installation then I'm not sure if it will work. If you start changing namespaces (as you said above) then this will very likely cause problems.

**Comment by jojogh** [comment] 2019-08-15 08:02
d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingfxforwardengine.cpp
d:\project\tsquarexl\quantlib\ql\qle\pricingengines\discountingcurrencyswapengine.cpp
both files are from ore, for the same namespace i just changed the namespace of both file into quantlib. Quantlib is not supporting FX derivatives.

**Comment by QuaternionRisk** [comment] 2019-08-15 08:10
That is your problem, if you are changing namespaces in the code then you will get unresolved symbols, that should not be a surprise.

In summary, ORE supports MSVC14.1. I feel this can be closed.

**Comment by jojogh** [comment] 2019-08-15 08:11
why i use MSVC 14.0 is ok, change to the MSVC 14.1, it is failed?

**Comment by QuaternionRisk** [comment] 2019-08-15 08:15
Not sure, but different compilers handle unresolved symbols differently.
Does it work with ORE out of the box?

**Comment by jojogh** [comment] 2019-08-15 08:17
yes, it is working well when ORE is built independently.

**Comment by QuaternionRisk** [comment] 2019-08-15 08:39
Great, so that confirms it works. I'll close this ticket.

**Closed by QuaternionRisk** 2019-08-15 08:39 UTC

**Comment by jojogh** [comment] 2019-08-15 08:44
Thanks a lot.
